pipelines:
  branches:
    master:
      - step:
          name: Deploying on 159.203.122.26
          script:
            - pipe: atlassian/ssh-run:0.2.6
              variables:
                SSH_USER: "root"
                SERVER: "159.203.122.26"
                COMMAND: "/root/clone.sh"
                MODE: "command"
